--------------------------------------------------------------------------------
-- USER & FOLLOW TABLES
--------------------------------------------------------------------------------

-- =====================
-- 사용자 테이블
-- =====================
CREATE TABLE SHORTFORM_USERS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    USERNAME VARCHAR2(200) NOT NULL UNIQUE,
    MAIL VARCHAR2(200) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(200) NOT NULL,
    PROFILE_IMG CLOB NOT NULL,          -- 프로필 파일 이미지 이름
    PROFILE_IMG_SRC CLOB NOT NULL,      -- 프로필 파일 이미지 경로
    BIO CLOB,                           -- 자기소개말
    MENTION VARCHAR2(300) NOT NULL UNIQUE,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =====================
-- 팔로우 관계 테이블
-- =====================
CREATE TABLE SHORTFORM_USERS_FOLLOWS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    FOLLOW_USER_ID NUMBER NOT NULL,     -- 팔로우한(요청한) 유저의 ID
    FOLLOWED_USER_ID NUMBER NOT NULL,   -- 팔로우된(상대방) 유저의 ID
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_FOLLOW_USER FOREIGN KEY (FOLLOW_USER_ID) REFERENCES SHORTFORM_USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_FOLLOWED_USER FOREIGN KEY (FOLLOWED_USER_ID) REFERENCES SHORTFORM_USERS(ID) ON DELETE CASCADE,
    CONSTRAINT UC_FOLLOW UNIQUE (FOLLOW_USER_ID, FOLLOWED_USER_ID),
    CONSTRAINT CK_NOT_SELF_FOLLOW CHECK (FOLLOW_USER_ID != FOLLOWED_USER_ID)
);

--------------------------------------------------------------------------------
-- VIDEO SYSTEM
--------------------------------------------------------------------------------

-- =====================
-- 비디오 테이블
-- =====================
CREATE TABLE SHORTFORM_VIDEOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    VIDEO_TITLE VARCHAR2(200) NOT NULL,
    VIDEO_DESCRIPTION CLOB,
    VIDEO_NAME VARCHAR2(1000) NOT NULL,
    VIDEO_SRC VARCHAR2(1000) NOT NULL,
    VIDEO_TAG VARCHAR2(500),
    VIDEO_VIEWS NUMBER DEFAULT 0,
    VIDEO_LOC VARCHAR2(500) NOT NULL UNIQUE,
    UPLOADER_USER_ID NUMBER NOT NULL,
    VIDEO_WATCH_AVAILABILITY VARCHAR2(50) NOT NULL CHECK (VIDEO_WATCH_AVAILABILITY IN ('public', 'followers', 'private')),
    COMMENT_AVAILABILITY VARCHAR2(50) NOT NULL CHECK (COMMENT_AVAILABILITY IN ('public', 'followers', 'private')),
    UPLOAD_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_UPLOADER FOREIGN KEY (UPLOADER_USER_ID) REFERENCES SHORTFORM_USERS(ID) ON DELETE CASCADE
);

-- =====================
-- 비디오 좋아요 테이블
-- =====================
CREATE TABLE SHORTFORM_VIDEO_LIKES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    LIKE_VIDEO_ID NUMBER NOT NULL,
    LIKER_USER_ID NUMBER NOT NULL,
    LIKE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LIKE_VIDEO FOREIGN KEY (LIKE_VIDEO_ID) REFERENCES SHORTFORM_VIDEOS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_LIKER_USER FOREIGN KEY (LIKER_USER_ID) REFERENCES SHORTFORM_USERS(ID) ON DELETE CASCADE,
    CONSTRAINT UC_VIDEO_LIKE UNIQUE (LIKE_VIDEO_ID, LIKER_USER_ID)
);

-- =====================
-- 비디오 댓글 테이블
-- =====================
CREATE TABLE SHORTFORM_COMMENTS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    COMMENT_TEXT CLOB NOT NULL,
    COMMENT_USER_ID NUMBER NOT NULL,
    COMMENT_VIDEO_ID NUMBER NOT NULL,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_COMMENT_USER FOREIGN KEY (COMMENT_USER_ID) REFERENCES SHORTFORM_USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_COMMENT_VIDEO FOREIGN KEY (COMMENT_VIDEO_ID) REFERENCES SHORTFORM_VIDEOS(ID) ON DELETE CASCADE
);

-- =====================
-- 비디오 댓글 좋아요 테이블
-- =====================
CREATE TABLE SHORTFORM_COMMENT_LIKES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    COMMENT_ID NUMBER NOT NULL,
    LIKER_USER_ID NUMBER NOT NULL,
    LIKE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_COMMENT_LIKE_COMMENT FOREIGN KEY (COMMENT_ID) REFERENCES SHORTFORM_COMMENTS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_COMMENT_LIKE_USER FOREIGN KEY (LIKER_USER_ID) REFERENCES SHORTFORM_USERS(ID) ON DELETE CASCADE,
    CONSTRAINT UC_COMMENT_LIKE UNIQUE (COMMENT_ID, LIKER_USER_ID)
);

-- =====================
-- 비디오 대댓글 테이블
-- =====================
CREATE TABLE SHORTFORM_COMMENT_REPLYS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    COMMENT_REPLY_TEXT CLOB NOT NULL,
    COMMENT_REPLY_USER_ID NUMBER NOT NULL,
    COMMENT_REPLY_ID NUMBER NOT NULL,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_REPLY_USER FOREIGN KEY (COMMENT_REPLY_USER_ID) REFERENCES SHORTFORM_USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_REPLY_COMMENT FOREIGN KEY (COMMENT_REPLY_ID) REFERENCES SHORTFORM_COMMENTS(ID) ON DELETE CASCADE
);

-- =====================
-- 비디오 대댓글 좋아요 테이블
-- =====================
CREATE TABLE SHORTFORM_REPLY_LIKES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    REPLY_ID NUMBER NOT NULL,
    LIKER_USER_ID NUMBER NOT NULL,
    LIKE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_REPLY_LIKE_REPLY FOREIGN KEY (REPLY_ID) REFERENCES SHORTFORM_COMMENT_REPLYS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_REPLY_LIKE_USER FOREIGN KEY (LIKER_USER_ID) REFERENCES SHORTFORM_USERS(ID) ON DELETE CASCADE,
    CONSTRAINT UC_REPLY_LIKE UNIQUE (REPLY_ID, LIKER_USER_ID)
);

--------------------------------------------------------------------------------
-- USER ACTIVITY (검색, 시청기록)
--------------------------------------------------------------------------------

-- =====================
-- 검색 기록 테이블
-- =====================
CREATE TABLE SHORTFORM_SEARCH_LISTS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    SEARCHED_USER_ID NUMBER,
    SEARCHED_WORD VARCHAR2(500) NOT NULL,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SEARCHED_USER_ID FOREIGN KEY (SEARCHED_USER_ID) REFERENCES SHORTFORM_USERS(ID) ON DELETE SET NULL
);

-- =====================
-- 시청 기록 테이블
-- =====================
CREATE TABLE SHORTFORM_VIEWSTORYS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    WATCHED_VIDEO_ID NUMBER NOT NULL,
    WATCHED_USER_ID NUMBER NOT NULL,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_WATCHED_VIDEO FOREIGN KEY (WATCHED_VIDEO_ID) REFERENCES SHORTFORM_VIDEOS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_WATCHED_USER FOREIGN KEY (WATCHED_USER_ID) REFERENCES SHORTFORM_USERS(ID) ON DELETE CASCADE
);

--------------------------------------------------------------------------------
-- COMMUNITY SYSTEM
--------------------------------------------------------------------------------

-- =====================
-- 커뮤니티 테이블
-- =====================
CREATE TABLE SHORTFORM_COMMUNITYS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    COMMUNITY_TEXT CLOB,
    COMMUNITY_WRITER_ID NUMBER NOT NULL,
    COMMUNITY_UUID VARCHAR2(50) NOT NULL UNIQUE,
    COMMUNITY_AVAILABILITY VARCHAR2(50) NOT NULL CHECK (COMMUNITY_AVAILABILITY IN ('public', 'followers', 'private')),
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_COMMUNITY_WRITER FOREIGN KEY (COMMUNITY_WRITER_ID) REFERENCES SHORTFORM_USERS(ID) ON DELETE CASCADE
);

-- =====================
-- 커뮤니티 추가 미디어 테이블
-- =====================
CREATE TABLE SHORTFORM_COMMUNITY_ADDITIONS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    FILE_SRC VARCHAR2(500) NOT NULL,
    COMMUNITY_ID NUMBER NOT NULL,
    UPLOAD_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ADDITION_COMMUNITY FOREIGN KEY (COMMUNITY_ID) REFERENCES SHORTFORM_COMMUNITYS(ID) ON DELETE CASCADE
);

-- =====================
-- 커뮤니티 좋아요 테이블
-- =====================
CREATE TABLE SHORTFORM_COMMUNITY_LIKES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    COMMUNITY_ID NUMBER NOT NULL,
    LIKER_USER_ID NUMBER NOT NULL,
    LIKE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_COMMUNITY_LIKE_COMMUNITY FOREIGN KEY (COMMUNITY_ID) REFERENCES SHORTFORM_COMMUNITYS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_COMMUNITY_LIKE_USER FOREIGN KEY (LIKER_USER_ID) REFERENCES SHORTFORM_USERS(ID) ON DELETE CASCADE,
    CONSTRAINT UC_COMMUNITY_LIKE UNIQUE (COMMUNITY_ID, LIKER_USER_ID)
);

-- =====================
-- 커뮤니티 댓글 테이블
-- =====================
CREATE TABLE SHORTFORM_COMMUNITY_COMMENTS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    COMMENT_TEXT CLOB NOT NULL,
    COMMENT_USER_ID NUMBER NOT NULL,
    COMMUNITY_ID NUMBER NOT NULL,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_COMMUNITY_COMMENT_USER FOREIGN KEY (COMMENT_USER_ID) REFERENCES SHORTFORM_USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_COMMUNITY_COMMENT_COMMUNITY FOREIGN KEY (COMMUNITY_ID) REFERENCES SHORTFORM_COMMUNITYS(ID) ON DELETE CASCADE
);

-- =====================
-- 커뮤니티 댓글 좋아요
-- =====================
CREATE TABLE SHORTFORM_COMMUNITY_COMMENT_LIKES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    LIKER_USER_ID NUMBER NOT NULL,
    COMMENT_ID NUMBER NOT NULL,
    LIKE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_COMMUNITY_COMMENT_LIKE_USER FOREIGN KEY (LIKER_USER_ID) REFERENCES SHORTFORM_USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_COMMUNITY_COMMENT_LIKE_COMMENT FOREIGN KEY (COMMENT_ID) REFERENCES SHORTFORM_COMMUNITY_COMMENTS(ID) ON DELETE CASCADE,
    CONSTRAINT UC_COMMUNITY_COMMENT_LIKE UNIQUE (COMMENT_ID, LIKER_USER_ID)
);

-- =====================
-- 커뮤니티 대댓글 테이블
-- =====================
CREATE TABLE SHORTFORM_COMMUNITY_COMMENT_REPLYS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    REPLY_TEXT CLOB NOT NULL,
    REPLY_USER_ID NUMBER NOT NULL,
    COMMENT_ID NUMBER NOT NULL,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_COMMUNITY_REPLY_USER FOREIGN KEY (REPLY_USER_ID) REFERENCES SHORTFORM_USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_COMMUNITY_REPLY_COMMENT FOREIGN KEY (COMMENT_ID) REFERENCES SHORTFORM_COMMUNITY_COMMENTS(ID) ON DELETE CASCADE
);

-- =====================
-- 커뮤니티 대댓글 좋아요 테이블
-- =====================
CREATE TABLE SHORTFORM_COMMUNITY_COMMENT_REPLY_LIKES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    REPLY_ID NUMBER NOT NULL,
    LIKER_USER_ID NUMBER NOT NULL,
    LIKE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_COMMUNITY_REPLY_LIKE_REPLY FOREIGN KEY (REPLY_ID) REFERENCES SHORTFORM_COMMUNITY_COMMENT_REPLYS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_COMMUNITY_REPLY_LIKE_USER FOREIGN KEY (LIKER_USER_ID) REFERENCES SHORTFORM_USERS(ID) ON DELETE CASCADE,
    CONSTRAINT UC_COMMUNITY_REPLY_LIKE UNIQUE (REPLY_ID, LIKER_USER_ID)
);

--------------------------------------------------------------------------------
-- INDEXES
--------------------------------------------------------------------------------

-- 비디오 관련 인덱스
CREATE INDEX IDX_VIDEOS_UPLOADER ON SHORTFORM_VIDEOS (UPLOADER_USER_ID);
CREATE INDEX IDX_VIDEOS_UPLOAD_AT ON SHORTFORM_VIDEOS (UPLOAD_AT);
CREATE INDEX IDX_COMMENTS_VIDEO ON SHORTFORM_COMMENTS (COMMENT_VIDEO_ID);
CREATE INDEX IDX_FOLLOWS_FOLLOWING ON SHORTFORM_USERS_FOLLOWS (FOLLOWED_USER_ID);
CREATE INDEX IDX_VIDEO_LIKES_VIDEO ON SHORTFORM_VIDEO_LIKES (LIKE_VIDEO_ID);
CREATE INDEX IDX_VIEWSTORYS_USER ON SHORTFORM_VIEWSTORYS (WATCHED_USER_ID);
CREATE INDEX IDX_VIEWSTORYS_VIDEO ON SHORTFORM_VIEWSTORYS (WATCHED_VIDEO_ID);

-- 커뮤니티 관련 인덱스
CREATE INDEX IDX_COMMUNITY_WRITER ON SHORTFORM_COMMUNITYS (COMMUNITY_WRITER_ID);
CREATE INDEX IDX_COMMUNITY_CREATE_AT ON SHORTFORM_COMMUNITYS (CREATE_AT);
CREATE INDEX IDX_COMMUNITY_AVAILABILITY ON SHORTFORM_COMMUNITYS (COMMUNITY_AVAILABILITY);
CREATE INDEX IDX_COMMUNITY_COMMENTS_COMMUNITY ON SHORTFORM_COMMUNITY_COMMENTS (COMMUNITY_ID);
CREATE INDEX IDX_COMMUNITY_COMMENTS_USER ON SHORTFORM_COMMUNITY_COMMENTS (COMMENT_USER_ID);
CREATE INDEX IDX_COMMUNITY_LIKES_COMMUNITY ON SHORTFORM_COMMUNITY_LIKES (COMMUNITY_ID);
CREATE INDEX IDX_COMMUNITY_LIKES_USER ON SHORTFORM_COMMUNITY_LIKES (LIKER_USER_ID);
CREATE INDEX IDX_COMMUNITY_ADDITIONS_COMMUNITY ON SHORTFORM_COMMUNITY_ADDITIONS (COMMUNITY_ID);




































