-- 1-1. IS_SOCIAL 컬럼을 NULL 허용, DEFAULT 0으로 추가
ALTER TABLE SHORTFORM_USERS ADD (
    IS_SOCIAL NUMBER(1) DEFAULT 0 NULL
);

-- 1-2. PROVIDER 컬럼을 NULL 허용, DEFAULT 'LOCAL'으로 추가
ALTER TABLE SHORTFORM_USERS ADD (
    PROVIDER VARCHAR2(50) DEFAULT 'LOCAL' NULL
);

-- 기존 레코드 중 NULL인 컬럼에 기본값 업데이트
-- 컬럼 추가 직후라면 모든 기존 레코드가 이 조건에 해당됩니다.
UPDATE SHORTFORM_USERS
SET
    IS_SOCIAL = 0,
    PROVIDER = 'LOCAL'
WHERE
    IS_SOCIAL IS NULL OR PROVIDER IS NULL;

-- 3-1. IS_SOCIAL 컬럼에 NOT NULL 제약 조건 추가
-- DEFAULT 제약 조건이 남아있으므로, 앞으로 INSERT 시 값을 지정하지 않아도 0이 들어갑니다.
ALTER TABLE SHORTFORM_USERS MODIFY (
    IS_SOCIAL NOT NULL
);

-- 3-2. PROVIDER 컬럼에 NOT NULL 제약 조건 추가
-- DEFAULT 제약 조건이 남아있으므로, 앞으로 INSERT 시 값을 지정하지 않아도 'LOCAL'이 들어갑니다.
ALTER TABLE SHORTFORM_USERS MODIFY (
    PROVIDER NOT NULL
);