-- 알림 테이블
-- (로컬은 ddl-auto:update가 엔티티에서 자동 생성. 운영(validate)에서는 이 DDL을 사전 적용)
CREATE TABLE SHORTFORM_NOTIFICATIONS (
    ID                    NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    RECIPIENT_USER_ID     NUMBER NOT NULL,
    ACTOR_USER_ID         NUMBER,
    ACTOR_USERNAME        VARCHAR2(200),
    ACTOR_MENTION         VARCHAR2(300),
    ACTOR_PROFILE_IMG_SRC VARCHAR2(1000),
    TYPE                  VARCHAR2(50) NOT NULL,
    TARGET_TYPE           VARCHAR2(50),
    TARGET_ID             VARCHAR2(300),
    MESSAGE               CLOB,
    IS_READ               NUMBER(1) DEFAULT 0 NOT NULL,
    CREATE_AT             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 수신자별 미읽음 조회 가속
CREATE INDEX IDX_NOTI_RECIPIENT ON SHORTFORM_NOTIFICATIONS (RECIPIENT_USER_ID, IS_READ);
