-- =====================================================
-- 신고 시스템 테이블 설계
-- =====================================================

-- 신고 테이블 (범용, [영상, 영상 댓글, 영상 댓글의 답글, 커뮤니티 게시글, 게시글 댓글, 게시글 댓글의 답글])
CREATE TABLE SHORTFORM_REPORTS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,

    -- 신고 대상 (Polymorphic 방식)
    TARGET_TYPE VARCHAR2(50) NOT NULL CHECK (TARGET_TYPE IN (
        'VIDEO',
        'COMMENT',
        'COMMENT_REPLY',
        'COMMUNITY',
        'COMMUNITY_COMMENT',
        'COMMUNITY_COMMENT_REPLY'
    )),
    TARGET_ID NUMBER NOT NULL,          -- 대상의 실제 ID
    REPORTER_USER_ID NUMBER NOT NULL,   -- 신고자 정보
    REPORTED_USER_ID NUMBER NOT NULL,   -- 피신고자 정보 (신고된 콘텐츠의 작성자)

    -- 신고 유형 (Enum으로 관리)
    REPORT_TYPE VARCHAR2(50) NOT NULL CHECK (REPORT_TYPE IN (
        'INAPPROPRIATE',    -- 부적절한 콘텐츠
        'SEXUAL',          -- 선정적인 콘텐츠
        'VIOLENCE',        -- 폭력적인 콘텐츠
        'HATE_SPEECH',     -- 혐오 발언
        'SPAM',            -- 스팸/광고
        'COPYRIGHT',       -- 저작권 침해
        'FALSE_INFO',      -- 허위 정보
        'PRIVACY',         -- 개인정보 침해
        'ILLEGAL',         -- 불법 콘텐츠
        'ETC'              -- 기타
    )),

    -- 신고 처리 상태
    STATUS VARCHAR2(50) DEFAULT 'PENDING' NOT NULL CHECK (STATUS IN (
        'PENDING',      -- 대기 중
        'REVIEWING',    -- 검토 중
        'APPROVED',     -- 승인 (신고 타당함)
        'REJECTED',     -- 기각 (신고 부당함)
        'RESOLVED'      -- 해결됨
    )),

    -- 관리자 검토 정보
    REVIEW_COMMENT CLOB, -- 검토 의견
    REVIEWED_AT TIMESTAMP,

    -- 조치 결과
    ACTION_TAKEN VARCHAR2(50) CHECK (ACTION_TAKEN IN (
        'NONE',           -- 조치 없음
        'WARNING',        -- 경고
        'CONTENT_HIDDEN', -- 콘텐츠 숨김
        'CONTENT_DELETED',-- 콘텐츠 삭제
        'USER_SUSPENDED', -- 사용자 정지
        'USER_BANNED'     -- 사용자 영구 차단
    )),

    -- 시간 정보
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,

    -- 외래키 제약조건
    CONSTRAINT FK_REPORT_REPORTER FOREIGN KEY (REPORTER_USER_ID) REFERENCES SHORTFORM_USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_REPORT_REPORTED_USER FOREIGN KEY (REPORTED_USER_ID) REFERENCES SHORTFORM_USERS(ID) ON DELETE CASCADE,

    -- 중복 신고 방지 (동일 사용자가 동일 콘텐츠를 중복 신고 불가)
    CONSTRAINT UK_REPORT_UNIQUE UNIQUE (REPORTER_USER_ID, TARGET_TYPE, TARGET_ID)
);

-- 2. 인덱스 생성 (성능 최적화)
CREATE INDEX IDX_REPORTS_TARGET ON SHORTFORM_REPORTS(TARGET_TYPE, TARGET_ID);
CREATE INDEX IDX_REPORTS_REPORTER ON SHORTFORM_REPORTS(REPORTER_USER_ID);
CREATE INDEX IDX_REPORTS_REPORTED ON SHORTFORM_REPORTS(REPORTED_USER_ID);
CREATE INDEX IDX_REPORTS_STATUS ON SHORTFORM_REPORTS(STATUS);
CREATE INDEX IDX_REPORTS_TYPE ON SHORTFORM_REPORTS(REPORT_TYPE);
CREATE INDEX IDX_REPORTS_CREATED ON SHORTFORM_REPORTS(CREATED_AT);

-- 밑에 주석 처리된 거는 사용하고 싶을 때 알아서 사용

-- 신고 통계 뷰 (선택사항 - 관리자 대시보드용)
-- CREATE OR REPLACE VIEW VW_REPORT_STATISTICS AS
-- SELECT
--     TARGET_TYPE,
--     REPORT_TYPE,
--     STATUS,
--     COUNT(*) AS REPORT_COUNT,
--     COUNT(DISTINCT REPORTER_USER_ID) AS UNIQUE_REPORTERS,
--     COUNT(DISTINCT REPORTED_USER_ID) AS UNIQUE_REPORTED_USERS
-- FROM SHORTFORM_REPORTS
-- GROUP BY TARGET_TYPE, REPORT_TYPE, STATUS;

-- 사용자별 신고 누적 통계 뷰
-- CREATE OR REPLACE VIEW VW_USER_REPORT_STATS AS
-- SELECT
--     REPORTED_USER_ID,
--     COUNT(*) AS TOTAL_REPORTS,
--     COUNT(CASE WHEN STATUS = 'APPROVED' THEN 1 END) AS APPROVED_REPORTS,
--     COUNT(CASE WHEN STATUS = 'REJECTED' THEN 1 END) AS REJECTED_REPORTS,
--     COUNT(CASE WHEN ACTION_TAKEN IN ('USER_SUSPENDED', 'USER_BANNED') THEN 1 END) AS PENALTIES
-- FROM SHORTFORM_REPORTS
-- GROUP BY REPORTED_USER_ID;

-- =====================================================
-- 사용 예시 쿼리
-- =====================================================

-- 1. 영상 신고
/*
INSERT INTO SHORTFORM_REPORTS (
    TARGET_TYPE, TARGET_ID, REPORTER_USER_ID, REPORTED_USER_ID, REPORT_TYPE, REPORT_REASON
) VALUES (
    'VIDEO', 123, 456, 789, 'SEXUAL', '선정적인 내용이 포함되어 있습니다.'
);
*/

-- 2. 커뮤니티 게시글 신고
/*
INSERT INTO SHORTFORM_REPORTS (
    TARGET_TYPE, TARGET_ID, REPORTER_USER_ID, REPORTED_USER_ID, REPORT_TYPE, REPORT_REASON
) VALUES (
    'COMMUNITY', 456, 123, 789, 'HATE_SPEECH', '혐오 발언이 포함되어 있습니다.'
);
*/

-- 3. 특정 콘텐츠에 대한 모든 신고 조회
/*
SELECT r.*, 
       reporter.USERNAME AS REPORTER_NAME,
       reported.USERNAME AS REPORTED_NAME
FROM SHORTFORM_REPORTS r
JOIN SHORTFORM_USERS reporter ON r.REPORTER_USER_ID = reporter.ID
JOIN SHORTFORM_USERS reported ON r.REPORTED_USER_ID = reported.ID
WHERE r.TARGET_TYPE = 'VIDEO' 
  AND r.TARGET_ID = 123
ORDER BY r.CREATED_AT DESC;
*/

-- 4. 대기 중인 신고 목록 조회
/*
SELECT r.*,
       reporter.USERNAME AS REPORTER_NAME,
       reported.USERNAME AS REPORTED_NAME,
       CASE r.TARGET_TYPE
           WHEN 'VIDEO' THEN v.VIDEO_TITLE
           WHEN 'COMMUNITY' THEN SUBSTR(c.COMMUNITY_TEXT, 1, 50)
           WHEN 'COMMENT' THEN SUBSTR(cm.COMMENT_TEXT, 1, 50)
       END AS TARGET_CONTENT
FROM SHORTFORM_REPORTS r
JOIN SHORTFORM_USERS reporter ON r.REPORTER_USER_ID = reporter.ID
JOIN SHORTFORM_USERS reported ON r.REPORTED_USER_ID = reported.ID
LEFT JOIN SHORTFORM_VIDEOS v ON r.TARGET_TYPE = 'VIDEO' AND r.TARGET_ID = v.ID
LEFT JOIN SHORTFORM_COMMUNITYS c ON r.TARGET_TYPE = 'COMMUNITY' AND r.TARGET_ID = c.ID
LEFT JOIN SHORTFORM_COMMENTS cm ON r.TARGET_TYPE = 'COMMENT' AND r.TARGET_ID = cm.ID
WHERE r.STATUS = 'PENDING'
ORDER BY r.CREATED_AT DESC;
*/

-- 5. 특정 사용자가 받은 신고 통계
/*
SELECT 
    TARGET_TYPE,
    REPORT_TYPE,
    STATUS,
    COUNT(*) AS COUNT
FROM SHORTFORM_REPORTS
WHERE REPORTED_USER_ID = 789
GROUP BY TARGET_TYPE, REPORT_TYPE, STATUS;
*/

-- 6. 신고 처리 (관리자)
/*
UPDATE SHORTFORM_REPORTS
SET STATUS = 'APPROVED',
    ACTION_TAKEN = 'CONTENT_HIDDEN',
    REVIEWER_ID = 1,  -- 관리자 ID
    REVIEW_COMMENT = '부적절한 콘텐츠로 확인되어 숨김 처리합니다.',
    REVIEWED_AT = CURRENT_TIMESTAMP,
    UPDATED_AT = CURRENT_TIMESTAMP
WHERE ID = 123;
*/