CREATE TABLE SHORTFORM_REPORTS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VIDEO_ID NUMBER NOT NULL,
    REPORTER_USER_ID NUMBER NOT NULL,
    REPORTED_USER_ID NUMBER NOT NULL,
    TYPE VARCHAR2(300) NOT NULL,
    PROCESSED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT UK_REPORT UNIQUE (VIDEO_ID, REPORTER_USER_ID)
);
