ALTER TABLE SHORTFORM_VIDEOS                    ADD COLUMN DELETE_YN NUMBER(1) DEFAULT 0;
ALTER TABLE SHORTFORM_COMMENTS                  ADD COLUMN DELETE_YN NUMBER(1) DEFAULT 0;
ALTER TABLE SHORTFORM_COMMENT_REPLYS            ADD COLUMN DELETE_YN NUMBER(1) DEFAULT 0;
ALTER TABLE SHORTFORM_SEARCH_LISTS              ADD COLUMN DELETE_YN NUMBER(1) DEFAULT 0;
ALTER TABLE SHORTFORM_COMMUNITYS                ADD COLUMN DELETE_YN NUMBER(1) DEFAULT 0;
ALTER TABLE SHORTFORM_COMMUNITY_COMMENTS        ADD COLUMN DELETE_YN NUMBER (1) DEFAULT 0;
ALTER TABLE SHORTFORM_COMMUNITY_COMMENT_REPLYS  ADD COLUMN DELETE_YN NUMBER(1) DEFAULT 0;